#!/bin/bash

chmod +x rawhttpget
chmod +x rawhttpget.py

if [ "$#" == "1" ]; then
    iptables -A OUTPUT -p tcp --tcp-flags RST RST -j DROP
    python rawhttpget.py $1
else
    echo "Please provide only url as a parameter"
    exit
fi
